### ISSUE TITLE
add the choice of db 

### ISSUE THREAD

**Issue by alphaleadership** [atplus-digital/pftp#8]
add mongodb

**Comment by alphaleadership** [comment]
@atplus-digital

**Comment by Luskan777** [comment]
Hi @alphaleadership ,

Sorry for the delay in replying.
I don't think it's interesting to support another database for the application, we use PureFTPD for the FTP server, it only supports Mysql, so we use the same database for the Web application and FTP to not make it difficult to manage the application.
